services:
  - type: web
    name: vis-meet-frontend
    env: node
    buildCommand: npm run build:render
    startCommand: npm run start:render
    envVars:
      - key: NODE_VERSION
        value: 20.x
      - key: USE_MOCK_BACKEND
        value: "true"
      - key: RENDER
        value: "true"
    autoDeploy: true

  - type: web
    name: vis-meet-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_VERSION
        value: 20.x
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 10000
    autoDeploy: true 